final List<String> fuelType = [
  'Diesel',
  'Electric',
  'Hybrid',
  'Other',
  'Petrol'
];
final List<String> transmission = ['Automatic', 'Manual', 'Other', 'Semi-Auto'];
final List<String> brand = [
  'Audi',
  'BMW',
  'Ford',
  'Mercedes',
  'Skoda',
  'Toyota',
  'Volkswagen'
];
final List<String> model = [
  ' 1 Series',
  ' 2 Series',
  ' 3 Series',
  ' 4 Series',
  ' 5 Series',
  ' 6 Series',
  ' 7 Series',
  ' A Class',
  ' A1',
  ' A2',
  ' A3',
  ' A4',
  ' A5',
  ' A6',
  ' A7',
  ' A8',
  ' Amarok',
  ' Arteon',
  ' Auris',
  ' Avensis',
  ' Aygo',
  ' B Class',
  ' B-MAX',
  ' Beetle',
  ' C Class',
  ' C-HR',
  ' C-MAX',
  ' CC',
  ' CL Class',
  ' CLA Class',
  ' CLC Class',
  ' CLK',
  ' CLS Class',
  ' Caddy',
  ' Caddy Life',
  ' Caddy Maxi',
  ' Caddy Maxi Life',
  ' Camry',
  ' Caravelle',
  ' Citigo',
  ' Corolla',
  ' E Class',
  ' EcoSport',
  ' Edge',
  ' Eos',
  ' Escort',
  ' Fabia',
  ' Fiesta',
  ' Focus',
  ' Fox',
  ' Fusion',
  ' G Class',
  ' GL Class',
  ' GLA Class',
  ' GLB Class',
  ' GLC Class',
  ' GLE Class',
  ' GLS Class',
  ' GT86',
  ' Galaxy',
  ' Golf',
  ' Golf SV',
  ' Grand C-MAX',
  ' Grand Tourneo Connect',
  ' Hilux',
  ' IQ',
  ' Jetta',
  ' KA',
  ' Ka+',
  ' Kamiq',
  ' Karoq',
  ' Kodiaq',
  ' Kuga',
  ' Land Cruiser',
  ' M Class',
  ' M2',
  ' M3',
  ' M4',
  ' M5',
  ' M6',
  ' Mondeo',
  ' Mustang',
  ' Octavia',
  ' PROACE VERSO',
  ' Passat',
  ' Polo',
  ' Prius',
  ' Puma',
  ' Q2',
  ' Q3',
  ' Q5',
  ' Q7',
  ' Q8',
  ' R Class',
  ' R8',
  ' RAV4',
  ' RS3',
  ' RS4',
  ' RS5',
  ' RS6',
  ' RS7',
  ' Ranger',
  ' Rapid',
  ' Roomster',
  ' S Class',
  ' S-MAX',
  ' S3',
  ' S4',
  ' S5',
  ' S8',
  ' SL CLASS',
  ' SLK',
  ' SQ5',
  ' SQ7',
  ' Scala',
  ' Scirocco',
  ' Sharan',
  ' Shuttle',
  ' Streetka',
  ' Superb',
  ' Supra',
  ' T-Cross',
  ' T-Roc',
  ' TT',
  ' Tiguan',
  ' Tiguan Allspace',
  ' Touareg',
  ' Touran',
  ' Tourneo Connect',
  ' Tourneo Custom',
  ' Transit Tourneo',
  ' Up',
  ' Urban Cruiser',
  ' V Class',
  ' Verso',
  ' Verso-S',
  ' X-CLASS',
  ' X1',
  ' X2',
  ' X3',
  ' X4',
  ' X5',
  ' X6',
  ' Yaris',
  ' Yeti',
  ' Yeti Outdoor',
  ' Z3',
  ' Z4',
  ' i3',
  ' i8',
  '180',
  '200',
  '220',
  '230'
];
Map<String, int> brandmap = {
  'Audi': 0,
  'BMW': 1,
  'Ford': 2,
  'Mercedes': 3,
  'Skoda': 4,
  'Toyota': 5,
  'Volkswagen': 6
};
Map<String, int> modelmap = {
  ' 1 Series': 0,
  ' 2 Series': 1,
  ' 3 Series': 2,
  ' 4 Series': 3,
  ' 5 Series': 4,
  ' 6 Series': 5,
  ' 7 Series': 6,
  ' A Class': 7,
  ' A1': 8,
  ' A2': 9,
  ' A3': 10,
  ' A4': 11,
  ' A5': 12,
  ' A6': 13,
  ' A7': 14,
  ' A8': 15,
  ' Amarok': 16,
  ' Arteon': 17,
  ' Auris': 18,
  ' Avensis': 19,
  ' Aygo': 20,
  ' B Class': 21,
  ' B-MAX': 22,
  ' Beetle': 23,
  ' C Class': 24,
  ' C-HR': 25,
  ' C-MAX': 26,
  ' CC': 27,
  ' CL Class': 28,
  ' CLA Class': 29,
  ' CLC Class': 30,
  ' CLK': 31,
  ' CLS Class': 32,
  ' Caddy': 33,
  ' Caddy Life': 34,
  ' Caddy Maxi': 35,
  ' Caddy Maxi Life': 36,
  ' Camry': 37,
  ' Caravelle': 38,
  ' Citigo': 39,
  ' Corolla': 40,
  ' E Class': 41,
  ' EcoSport': 42,
  ' Edge': 43,
  ' Eos': 44,
  ' Escort': 45,
  ' Fabia': 46,
  ' Fiesta': 47,
  ' Focus': 48,
  ' Fox': 49,
  ' Fusion': 50,
  ' G Class': 51,
  ' GL Class': 52,
  ' GLA Class': 53,
  ' GLB Class': 54,
  ' GLC Class': 55,
  ' GLE Class': 56,
  ' GLS Class': 57,
  ' GT86': 58,
  ' Galaxy': 59,
  ' Golf': 60,
  ' Golf SV': 61,
  ' Grand C-MAX': 62,
  ' Grand Tourneo Connect': 63,
  ' Hilux': 64,
  ' IQ': 65,
  ' Jetta': 66,
  ' KA': 67,
  ' Ka+': 68,
  ' Kamiq': 69,
  ' Karoq': 70,
  ' Kodiaq': 71,
  ' Kuga': 72,
  ' Land Cruiser': 73,
  ' M Class': 74,
  ' M2': 75,
  ' M3': 76,
  ' M4': 77,
  ' M5': 78,
  ' M6': 79,
  ' Mondeo': 80,
  ' Mustang': 81,
  ' Octavia': 82,
  ' PROACE VERSO': 83,
  ' Passat': 84,
  ' Polo': 85,
  ' Prius': 86,
  ' Puma': 87,
  ' Q2': 88,
  ' Q3': 89,
  ' Q5': 90,
  ' Q7': 91,
  ' Q8': 92,
  ' R Class': 93,
  ' R8': 94,
  ' RAV4': 95,
  ' RS3': 96,
  ' RS4': 97,
  ' RS5': 98,
  ' RS6': 99,
  ' RS7': 100,
  ' Ranger': 101,
  ' Rapid': 102,
  ' Roomster': 103,
  ' S Class': 104,
  ' S-MAX': 105,
  ' S3': 106,
  ' S4': 107,
  ' S5': 108,
  ' S8': 109,
  ' SL CLASS': 110,
  ' SLK': 111,
  ' SQ5': 112,
  ' SQ7': 113,
  ' Scala': 114,
  ' Scirocco': 115,
  ' Sharan': 116,
  ' Shuttle': 117,
  ' Streetka': 118,
  ' Superb': 119,
  ' Supra': 120,
  ' T-Cross': 121,
  ' T-Roc': 122,
  ' TT': 123,
  ' Tiguan': 124,
  ' Tiguan Allspace': 125,
  ' Touareg': 126,
  ' Touran': 127,
  ' Tourneo Connect': 128,
  ' Tourneo Custom': 129,
  ' Transit Tourneo': 130,
  ' Up': 131,
  ' Urban Cruiser': 132,
  ' V Class': 133,
  ' Verso': 134,
  ' Verso-S': 135,
  ' X-CLASS': 136,
  ' X1': 137,
  ' X2': 138,
  ' X3': 139,
  ' X4': 140,
  ' X5': 141,
  ' X6': 142,
  ' Yaris': 143,
  ' Yeti': 144,
  ' Yeti Outdoor': 145,
  ' Z3': 146,
  ' Z4': 147,
  ' i3': 148,
  ' i8': 149,
  '180': 150,
  '200': 151,
  '220': 152,
  '230': 153
};
Map<String, int> fuelTypemap = {
  'Diesel': 0,
  'Electric': 1,
  'Hybrid': 2,
  'Other': 3,
  'Petrol': 4
};
Map<String, int> tranmissonmap = {
  'Automatic': 0,
  'Manual': 1,
  'Other': 2,
  'Semi-Auto': 3
};
